language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - python -m pip install -U pip
  - pip install -U numpy
  - pip install -U .
# command to run tests
script:
  - python setup.py test